### ISSUE TITLE
Add comment system

### ISSUE THREAD

**Issue by bigeagle** [scateu/scateu.github.io#1]
不能吐槽有木有！！！！

**Comment by scateu** [comment]
要啥自行车！

**Comment by bigeagle** [comment]
加一段 disqus 就可以了，搞一下嘛……

**Comment by scateu** [comment]
主要是我觉得这个博客主题丑的一逼... 打算找个时间再换一个，然后(原有的博客内容)(就又没有)(了).......

啊，我的手为什么突然被剁了....

**Comment by bigeagle** [comment]
内容把 markdown copy 过去不就行了…

**Comment by scateu** [comment]
没有勇气....

话说我这种不停扔掉旧博客的行为算不停的自我否定与自我进化与自我救赎与自我实现么...

**Comment by bigeagle** [comment]
你还是要多学习一下，知名校友胡锦涛同志曾提出「道路自信，理论自信，制度自信」

On Wed, Feb 4, 2015 at 3:21 PM, scateu notifications@github.com wrote:

> 没有勇气....
> 
> 话说我这种不停扔掉旧博客的行为算不停的自我否定与自我进化与自我救赎与自我实现么...
> 
> On Wed, Feb 4, 2015 at 3:15 PM, bigeagle notifications@github.com
> wrote:
> 
> > 内容把 markdown copy 过去不就行了…
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/scateu/scateu.github.io/issues/1#issuecomment-72801786>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/scateu/scateu.github.io/issues/1#issuecomment-72802321
> .

## 

Open Source, Open Mind

**Comment by scateu** [comment]
加好了！

迅速的自我修正

2015-02-04 15:22 GMT+08:00 bigeagle notifications@github.com:

> 你还是要多学习一下，知名校友胡锦涛同志曾提出「道路自信，理论自信，制度自信」
>

**Comment by bigeagle** [comment]
赞！

On Wed, Feb 4, 2015 at 3:38 PM, scateu notifications@github.com wrote:

> 加好了！
> 
> 迅速的自我修正
> 
> 2015-02-04 15:22 GMT+08:00 bigeagle notifications@github.com:
> 
> > 你还是要多学习一下，知名校友胡锦涛同志曾提出「道路自信，理论自信，制度自信」
> > 
> > On Wed, Feb 4, 2015 at 3:21 PM, scateu notifications@github.com
> > wrote:
> > 
> > > 没有勇气....
> > > 
> > > 话说我这种不停扔掉旧博客的行为算不停的自我否定与自我进化与自我救赎与自我实现么...
> > > 
> > > On Wed, Feb 4, 2015 at 3:15 PM, bigeagle notifications@github.com
> > > wrote:
> > > 
> > > > 内容把 markdown copy 过去不就行了…
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/scateu/scateu.github.io/issues/1#issuecomment-72801786>
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/scateu/scateu.github.io/issues/1#issuecomment-72802321>
> > 
> > > .
> > 
> > ## 
> > 
> > Open Source, Open Mind
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/scateu/scateu.github.io/issues/1#issuecomment-72802495>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/scateu/scateu.github.io/issues/1#issuecomment-72803828
> .

## 

Open Source, Open Mind

**Comment by anjue39** [comment]
这个blog源来自哪

**Comment by scateu** [comment]
> 这个blog源来自哪

根据jekyll的模认模板改的
